# GUI Constants
BG_COLOR = '#F5F5F5'
FONT_FAMILY = "Segoe UI"
FONT_SIZE = 12

# Color Constants
TITLE_COLOR = '#61afef'
SUBTITLE_COLOR = '#98c379'
DATA_COLOR = '#e5c07b'
DATA_LABEL_COLOR = '#abb2bf'
BACKGROUND_COLOR = '#282c34'
FRAME_BACKGROUND_COLOR = '#3e4451'

# Graph Constants
GRAPH_APM_COLOR = 'blue'
GRAPH_EAPM_COLOR = 'green'
GRAPH_ALPHA = 0.5
GRAPH_DPI = 100
GRAPH_FIGSIZE = (5, 4)

# Window Constants
MAIN_WINDOW_SIZE = "600x500"
MAIN_WINDOW_TITLE = "APM Tracker"

# Font Sizes
TITLE_FONT_SIZE = 24
SUBTITLE_FONT_SIZE = 14
DATA_FONT_SIZE = 20
LABEL_FONT_SIZE = 12
MINI_WINDOW_SIZE = 14

# Default Settings
DEFAULT_TRANSPARENCY = 1.0
DEFAULT_UPDATE_INTERVAL = 500  # milliseconds
DEFAULT_GRAPH_UPDATE_INTERVAL = 1000  # milliseconds
DEFAULT_GRAPH_TIME_RANGE = 60  # seconds
DEFAULT_MAX_ACTIONS_PER_SECOND = 50
DEFAULT_ACTION_COOLDOWN = 0.05  # seconds
DEFAULT_EAPM_COOLDOWN = 0.5  # seconds

# Graph Settings
GRAPH_TIME_RANGE_OPTIONS = [30, 60, 120, 300]  # seconds

# Logging Levels
LOG_LEVELS = ['DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL']

# File Paths
FONT_FILENAME = 'IosevkaTermNerdFont-Regular.ttf'
FONT_NAME= 'IosevkaTerm NF'
ICON_FILENAME = 'keebfire.png'

# Mini Window Constants
MINI_WINDOW_TITLE = "APM Tracker Mini"
MINI_WINDOW_BG_COLOR = '#2E3440'
MINI_WINDOW_APM_COLOR = '#88C0D0'
MINI_WINDOW_EAPM_COLOR = '#8FBCBB'
MINI_WINDOW_LABEL_COLOR = '#D8DEE9'
