# GUI Constants
BG_COLOR = '#F5F5F5'
FONT_FAMILY = "Segoe UI"
FONT_SIZE = 12

# Default Settings
DEFAULT_TRANSPARENCY = 1.0
DEFAULT_UPDATE_INTERVAL = 500  # milliseconds
DEFAULT_GRAPH_UPDATE_INTERVAL = 1000  # milliseconds
DEFAULT_GRAPH_TIME_RANGE = 60  # seconds
DEFAULT_MAX_ACTIONS_PER_SECOND = 50
DEFAULT_ACTION_COOLDOWN = 0.05  # seconds
DEFAULT_EAPM_COOLDOWN = 0.5  # seconds

# Graph Settings
GRAPH_TIME_RANGE_OPTIONS = [30, 60, 120, 300]  # seconds

# Logging Levels
LOG_LEVELS = ['DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL']
