name: Windows and Linux Build and Release APM Tracker

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller==6.10.0

      - name: Build Windows Executable
        run: |
          pyinstaller --name=APMTracker --windowed --add-data "icons;icons" --icon=icons/keebfire.ico --noconfirm apm.py

      - name: Verify executable name
        run: |
          if (Test-Path dist/APMTracker/APMTracker.exe) {
            Write-Host "APMTracker.exe created successfully"
          } else {
            Write-Error "APMTracker.exe not found in dist directory"
            exit 1
          }
        shell: pwsh

      - name: Archive Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: apm_tracker_windows
          path: dist/APMTracker

  build_linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller==6.10.0

      - name: Build Linux Executable
        run: |
          pyinstaller --name=APMTracker --windowed --add-data "icons:icons" --icon=icons/keebfire.png --noconfirm apm.py

      - name: Verify executable name
        run: |
          if [ -f "dist/APMTracker/APMTracker" ]; then
            echo "APMTracker created successfully"
          else
            echo "APMTracker not found in dist directory"
            exit 1
          fi

      - name: Archive Linux Executable
        uses: actions/upload-artifact@v4
        with:
          name: apm_tracker_linux
          path: dist/APMTracker

  release:
    needs: [build_windows, build_linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write

    steps:
      - name: Download Windows Executable
        uses: actions/download-artifact@v4
        with:
          name: apm_tracker_windows
          path: APMTracker_Windows

      - name: Download Linux Executable
        uses: actions/download-artifact@v4
        with:
          name: apm_tracker_linux
          path: APMTracker_Linux

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            APMTracker_Windows/**/*
            APMTracker_Linux/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
