name: Windows and Linux Build and Release APM Tracker
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.5'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller==6.10.0 matplotlib pillow
      - name: Build Windows Executable
        run: |
          $MatplotlibPath = python -c "import matplotlib; import os; print(os.path.dirname(matplotlib.__file__))"
          if ($LASTEXITCODE -ne 0) {
            Write-Error "Failed to find matplotlib path"
            exit 1
          }
          pyinstaller --onefile --noconsole --add-data "$MatplotlibPath;matplotlib" --add-data "assets/fonts;assets/fonts "--add-data "icons;icons" --icon="icons/keebfire.ico" --name="APMTracker" src/main.py
        shell: pwsh
      - name: Verify executable
        run: |
          if (Test-Path dist/APMTracker.exe) {
            Write-Host "APMTracker.exe created successfully"
          } else {
            Write-Error "APMTracker.exe not found in dist directory"
            exit 1
          }
        shell: pwsh
      - name: Archive Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: apm_tracker_windows
          path: dist/APMTracker.exe

  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.5'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller==6.10.0 matplotlib pillow
      - name: Build Linux Executable
        run: |
          MatplotlibPath=$(python -c "import matplotlib; import os; print(os.path.dirname(matplotlib.__file__))")
          pyinstaller --onefile --add-data "$MatplotlibPath:matplotlib" --add-data "assets/fonts:assets/fonts" --add-data "icons/keebfire.ico:." --add-data "icons:icons" --icon="icons/keebfire.png" --name="APMTracker" src/main.py
      - name: Verify executable
        run: |
          if [ -f "dist/APMTracker" ]; then
            echo "APMTracker created successfully"
          else
            echo "APMTracker not found in dist directory"
            exit 1
          fi
      - name: Archive Linux Executable
        uses: actions/upload-artifact@v4
        with:
          name: apm_tracker_linux
          path: dist/APMTracker

  release:
    needs: [build_windows, build_linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Download Windows Executable
        uses: actions/download-artifact@v4
        with:
          name: apm_tracker_windows
      - name: Download Linux Executable
        uses: actions/download-artifact@v4
        with:
          name: apm_tracker_linux
      - name: Display structure of downloaded files
        run: ls -R
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            APMTracker.exe
            APMTracker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
