name: Windows Build and Release APM Tracker

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller==6.10.0 matplotlib

      - name: Build Windows Executable
        run: |
          $MatplotlibPath = python -c "import matplotlib; import os; print(os.path.dirname(matplotlib.__file__))"
          if ($LASTEXITCODE -ne 0) {
            Write-Error "Failed to find matplotlib path"
            exit 1
          }
          pyinstaller --onefile --noconsole --add-data "$MatplotlibPath;matplotlib" apm.py
        shell: pwsh

      - name: List dist directory
        run: dir dist

      - name: Archive Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: apm_tracker_windows
          path: dist/apm.exe

  release:
    needs: build_windows
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write

    steps:
      - name: Download Windows Executable
        uses: actions/download-artifact@v4
        with:
          name: apm_tracker_windows

      - name: Display structure of downloaded files
        run: ls -R

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: apm.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
